### ISSUE TITLE
Kicad 6.0.5  Error with plugim

### ISSUE THREAD

**Issue by jfoxr** [Kriechi/kicad-library-WeAct-RP2040-Pico#1]
Kicad declares that Archive does not contain a valid metadata.json file. This is the latest pull from KiCad. Any ideas?

**Comment by Kriechi** [comment]
Sorry for the trouble - looks like the zip archive file generated by GitHub is not compatible with KiCad.

Please extract the zip file (or use a freshly cloned git repo) to create a new zip file without the additional top-level folders. The `manifest.json`, and all other files and folders next to it, need to be at the root of the zip file.

A working zip file looks like this:

```
git clone https://github.com/Kriechi/kicad-library-WeAct-RP2040-Pico.git
cd kicad-library-WeAct-RP2040-Pico.git
zip -r ~/working.zip *

unzip -l ~/working.zip
Archive:  /home/me/working.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  04-17-2022 15:52   3dmodels/
  8371761  04-17-2022 15:45   3dmodels/WeAct-RP2040-Pico.step
     1076  04-17-2022 15:45   LICENSE
     1783  04-17-2022 16:15   README.md
        0  04-17-2022 15:52   footprints/
        0  04-17-2022 15:52   footprints/WeAct-RP2040-Pico.pretty/
     8964  04-17-2022 16:13   footprints/WeAct-RP2040-Pico.pretty/WeAct-RP2040-Pico.kicad_mod
     1222  04-17-2022 15:56   metadata.json
        0  04-17-2022 15:52   symbols/
    11926  04-17-2022 15:45   symbols/WeAct-RP2040-Pico.kicad_sym
---------                     -------
  8396732                     10 files
```

I will update the instructions in the README accordingly - thanks for finding this!

**Comment by jfoxr** [comment]
That got it working. Thank you for the help and for making this model.
