### ISSUE TITLE
KiCad 6.0.9 footprint and symbols are not linked

### ISSUE THREAD

**Issue by dhruvinsh** [Kriechi/kicad-library-WeAct-RP2040-Pico#2]
I installed the plugin sucessfully but in schematic when I try to add the symbol, footprint is show up as blank.

![image](https://user-images.githubusercontent.com/33428164/205780036-4132fc79-393d-45d8-be30-58686f6ebeec.png)

I have double check the footprint installation and it looks fine. Same for the symbol as well.

**Comment by Kriechi** [comment]
Can you assign the matching footprint manually after inserting the symbol into your schematic?
It's possible only the default symbol-to-footprint assignment is missing...

**Comment by dhruvinsh** [comment]
Yes, you are right. When adding a part (as above) it do not show the footprint. But then running footprint assignment tool it give me option to select the RP2040 and that works.

Thanks.

**Comment by Kriechi** [comment]
@dhruvinsh thanks for flagging this - I just pushed a change that should now set the default footprint in the symbol.
If you want to test it, simple re-download and re-install the library. Then the correct footprint should be visible in the screenshot you shared originally.
